version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      - DB_HOST=mysqldb
      - DB_PORT=3306
      - DB_NAME=database_development
      - DB_USERNAME=root
      - DB_PASSWORD=password
    networks:
      - nodejs-mysql-network

  mysqldb:
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=database_development
      - MYSQL_ROOT_PASSWORD=password
    volumes:
       - mysql-data:/var/lib/mysql
    networks:
      - nodejs-mysql-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      retries: 10
      interval: 10s
      timeout: 60s

volumes:
  mysql-data:

networks:
  nodejs-mysql-network:
